### ISSUE TITLE
Example demo is not working properly

### ISSUE THREAD

**Issue by fullonic** [kylebarron/quantized-mesh-encoder#67]
Hi @kylebarron, 
I can't visualize proper your example demo: https://kylebarron.dev/quantized-mesh-encoder/

This is what I see:
![image](https://user-images.githubusercontent.com/13336073/185103164-d30beb6b-3754-463b-b1dd-7f3261e55523.png)

Looks like it's related to CORS
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 
https://us-east-1-lambda.kylebarron.dev/dem/mesh/13/1507/2820.terrain?url=terrarium&mesh_max_error=9.41&mesh_algorithm=pydelatin&flip_y=true. 
(Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 530.
```

**Comment by kylebarron** [comment]
After some abuse of my server, I decided to shut down my hosted demos rather than potentially be on the hook for $800/mo

https://twitter.com/kylebarron2/status/1412494170107920389?s=21&t=XoJXGz3Pql73l7qsk1IA-Q

**Comment by fullonic** [comment]
uauu! I'm sorry about that! 
Is there any documentation or blog post about deploying it locally? I really would like to test it. Thanks :)

**Comment by kylebarron** [comment]
The frontend code is in [`site`](https://github.com/kylebarron/quantized-mesh-encoder/tree/master/site). The backend code uses https://github.com/kylebarron/dem-tiler I think, though I haven't looked at it in a while and it might not run

**Comment by fullonic** [comment]
Thanks, @kylebarron! I'm closing this issue :+1:
